name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Enviar arquivos para hospedagem
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v6

      - name: Enviar arquivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          local-dir: ./
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            